services:
  db:
    image: postgres:17-alpine3.20
    restart: unless-stopped
    oom_score_adj: -500
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 5432
        published: '33371'
        protocol: tcp
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mw-db-network
      - dokploy-network
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}
      interval: 5s
      timeout: 10s
      retries: 20

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    oom_score_adj: -500
    command:
      - 'redis-server'
      - '--requirepass ${REDIS_PASSWORD}'
    volumes:
      - redis_data:/data
    networks:
      - mw-redis-network
      - dokploy-network
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 10s
      retries: 20

  app: &app
    build:
      context: ./
      dockerfile: docker/php/Dockerfile-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      COMMAND: php artisan octane:frankenphp --host=0.0.0.0 --port=80 --watch
      PROCESS: app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # Персистентні залежності - зберігаються між деплоями
      - ../files/vendor:/var/www/vendor
      - ../files/node_modules:/var/www/node_modules

      # Персистентне сховище Laravel
      - ../files/storage/app:/var/www/storage/app
      - ../files/storage/logs:/var/www/storage/logs
      - ../files/storage/framework/cache/data:/var/www/storage/framework/cache/data
      - ../files/storage/framework/sessions:/var/www/storage/framework/sessions
      - ../files/storage/framework/views:/var/www/storage/framework/views

      # Публічні файли (uploads)
      - ../files/public/storage:/var/www/public/storage
      - ../files/public:/var/www/public

      # Caddy
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

      # Кеші composer/npm
      - mw_app_composer_data:/.composer
      - mw_app_npm_data:/.npm
    expose:
      - '80'
      - '443'
      - '5173'
      - '9003'
    networks:
      - mw-db-network
      - mw-redis-network
      - dokploy-network
    healthcheck:
      test: curl -s http://localhost/up >/dev/null || exit 1
      interval: 5s
      timeout: 10s
      retries: 20

  workers:
    <<: *app
    environment:
      COMMAND: php artisan queue:work --sleep=1 --tries=3
      PROCESS: worker
      XDEBUG_MODE: 'off'
    networks:
      - mw-db-network
      - mw-redis-network
      - dokploy-network

  schedule:
    <<: *app
    environment:
      COMMAND: supercronic -quiet /var/www/docker/php/schedule/schedule
      PROCESS: schedule
      XDEBUG_MODE: 'off'
    networks:
      - mw-db-network
      - mw-redis-network
      - dokploy-network
    healthcheck:
      test: supercronic -test /var/www/docker/php/schedule/schedule | grep -q 'is valid'
      interval: 30s
      timeout: 10s
      retries: 2

  websockets:
    <<: *app
    environment:
      PROCESS: reverb
      XDEBUG_MODE: 'off'
      COMMAND: >
        php artisan reverb:start
        --host=0.0.0.0
        --port=8080
        --debug
    expose:
      - 8080
    networks:
      - mw-db-network
      - mw-redis-network
      - dokploy-network
    healthcheck:
      disable: true

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    environment:
      MP_UI_AUTH: ${MP_UI_AUTH}
    expose:
      - '1025'
      - '8025'
    networks:
      - mw-db-network
      - dokploy-network

volumes:
  db_data:
    driver: local
    name: mw_db_data
  redis_data:
    driver: local
    name: mw_redis_data
  caddy_data:
    driver: local
    name: mw_caddy_data
  caddy_config:
    driver: local
    name: mw_caddy_config
  mw_app_composer_data:
    driver: local
    name: mw_app_composer_data
  mw_app_npm_data:
    driver: local
    name: mw_app_npm_data

networks:
  mw-db-network:
    driver: bridge
  mw-redis-network:
    driver: bridge
    name: mw-redis-network
  dokploy-network:
    external: true
